CREATE TABLE IF NOT EXISTS machine_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL COLLATE NOCASE UNIQUE
);

INSERT OR IGNORE INTO machine_types (name)
SELECT DISTINCT TRIM(type) FROM machines
WHERE type IS NOT NULL AND TRIM(type) != '';
